"""empty message

Revision ID: adfb1a9a8b78
Revises: 227f509508ea
Create Date: 2023-10-16 15:23:06.549565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfb1a9a8b78'
down_revision = '227f509508ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('çplanet_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_planets_planet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['çplanet_id'], ['id'])
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_planets_planet_id_fkey', 'planets', ['planet_id'], ['id'])
        batch_op.drop_column('çplanet_id')

    # ### end Alembic commands ###
